### ISSUE TITLE
Separate capitalized words in the Lyrics column to section info and expression

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#14]
There are some two types of info in lyrics column of the SymbTr-txt files (apart from the lyrics themselves): section and expression. They are both capitalized. The full list is here: https://docs.google.com/spreadsheets/d/1ECake4PVvM_QZfRuThcYDWFZG572IW0wCqPesCmw0_E/edit?usp=sharing

We have marked which ones indicate section information. The expression elements should be converted to the appropriate notation symbol when doing the SymbTr-txt to MusicXML conversion.

**Comment by sertansenturk** [comment]
Note that some of the words marked as section in the excel document are instrumentation for a given interval. Note that this can be still regarded as a structural element (i.e. Saz girisi), so we don't distinguish them from the section names explicitly. They can be easily separated in the future if needed.

Second, the lyrics lines in the vocal compositions are indicated by spaces within the lyrics.

**Comment by burakuyar** [comment]
To be checked.

**Comment by burakuyar** [comment]
Checked. List is compared with Sertan's list on Google Docs. Currenly both are fine.
