### ISSUE TITLE
Txt files should be encoded in UTF-8.

### ISSUE THREAD

**Issue by burakuyar** [burakuyar/MusicXMLConverter#16]

**Comment by sertansenturk** [comment]
While reading SymbTr-txt files we should also make sure the file is encoded in UTF-8. IF not, we should send a warning/error and/or convert the file.

**Comment by sertansenturk** [comment]
In the symbtr repo, this is handled by travis.ci by the issue: https://github.com/MTG/SymbTr/commit/b1d364102ed279b4e12ad3659a8070c161574f03
