### ISSUE TITLE
Some score don't have a title

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#21]
Example: kurdilihicazkar--longa--nimsofyan----kemani_sebuh

**Comment by burakuyar** [comment]
This is because the title part in the file name (4th field) is empty. We can write Makam and Form as title in this kind of situations?

For the example above: Kurdilihicazkar Longa

**Comment by sertansenturk** [comment]
Yes, this is what we should do. Note that we should write the names with Turkish characters. For that you can refer to a makam dictionary such as [here](https://github.com/sertansenturk/turkish_makam_corpus_stats/blob/master/data/makamFormUsulDicts/makam_sheet.xlsx). You can disregard the entries irrelevant to SymbTr as I have explained earlier via mail.

**Comment by burakuyar** [comment]
Done.

~~Turkish names will be read from the file above.~~ use the excel sheets from turkish_makam_corpus_stats

**Comment by sertansenturk** [comment]
use the excel sheets from turkish_makam_corpus_stats

**Comment by sertansenturk** [comment]
this is addressed in more detail in #31
