### ISSUE TITLE
Saving the mappings in the txt to xml conversion

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#23]
When we are doing the conversion from one format to the other, we should keep track of a map between the elements. This is needed for linking the data between different formats and needed for several tasks (e.g. displaying the correct notes in the svg files in the audio score alignment which was done on the txt files)

**Comment by sertansenturk** [comment]
To be done after journal paper submission, can wait for now...

**Comment by burakuyar** [comment]
Kept in score.symbt2xmldict variable
