### ISSUE TITLE
Handling the "Kod"s properly

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#24]
In https://github.com/MTG/SymbTr/blob/master/code_explanations.xlsx, we have all the possible "Kod"s in the SymbTr files. How many of them are we handling correctly, e.g. when we observe "43" are we labeling it as and [inverted-mordent](http://www.musicxml.com/UserManuals/MusicXML/Content/EL-MusicXML-inverted-mordent.htm), or are we repeating the previous measure when we arrive to "35"?

**Comment by sertansenturk** [comment]
To help, I quickly extracted the current set of values the "Kod" field has in the collection. The values are:

[0, 1, 35, 4, 32, 7, 8, 9, 10, 11, 12, 44, 16, 43, 51, 53, 54, 23, 24, 55, 28]

Here is the [code](https://github.com/MTG/SymbTr/blob/master/extras/getSymbTrCodes.ipynb) to compute and its [output](https://github.com/MTG/SymbTr/blob/master/extras/unittests/data/note_codes.json) in json format.

**Comment by burakuyar** [comment]
I think this is a subset of what we mentioned in #22 . Currently, the whole code is being refactored to be able to easily add/change any attribute while doing the txt->xml conversion.

In the current version, Kods [0, 8, 9, 50, 51] are being handled. After the refactoring is done, the code will be easily understandable and modifyable for doing changes.

Thans for the data!

**Comment by burakuyar** [comment]
Kods [0,1,4,7,8,9,10,11,12,16,23,24,32,43,44,51] are handled.

Kods [23,24,43,44] are mordents. There is little confusion about the symbols. This will be fixed after Kemal's response.

Kod 35-measure repeat. The symbol is not being imported/exported by MuseScore. (https://musescore.org/en/node/21649/) As a quick fix, we can duplicate the repeated measures. (?)

Kods [28,53,54,55] will be handled asap.

**Comment by sertansenturk** [comment]
Maybe I can also help with the mordents. What is the confusion?

For 35 repeating the measures is fine...

**Comment by burakuyar** [comment]
[23,24,43,44] mordents are handled.
[28,53,54,55] grupetto, phrase boundaries and flavor start/ends are handled.

**Comment by sertansenturk** [comment]
anything left?

**Comment by burakuyar** [comment]
- [x] Kod1 -> Add comments in the musicxml file for these notes.
- [x] Kod11 -> Add comments in the musicxml file for these notes.
- [x] Kod35 -> validate
- [ ] Kod53,54,55 -> verify by asking in the music21 mail group

**Comment by sertansenturk** [comment]
The only remaining issue is referenced in #30
