### ISSUE TITLE
Get the metadata text from the mu2 files

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#31]
The metadata in the Symbtr-txt filenames are slugified, i.e. the Turkish special characters are not present. However we can obtain this information from the mu2 headers. [symbtrdataextractor](https://github.com/sertansenturk/symbtrdataextractor)] package has the modules to obtain this information.

Some of the relevant information are Title, (middle top), makam and usul (upper left), composer and lyricist (upper right). 

Note that the title would be empty in case the piece is instrumental. In this case we should concatanate and print the mu2_names of the makam and form of the piece in the title (e.g. Kürdilihicazkar Peşrev).

**Comment by sertansenturk** [comment]
Missing composer and lyricist

**Comment by burakuyar** [comment]
Done.
