### ISSUE TITLE
Change tempo to metronome

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#41]
As far as understand from the MusicXML specificaiton tempo is MIDI related and the unit is always a quarter note. We have to set the tempo from the metronome attribute: http://www.musicxml.com/UserManuals/MusicXML/Content/CT-MusicXML-metronome.htm

**Comment by burakuyar** [comment]
Metronome is added.
Tempo is kept because it effects the playback speed.
