### ISSUE TITLE
Copy the structure information in instrumental compositions

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#5]
Peşrev and sazsemaisi directly have the names written in the first note of the measure. This information  was checked/corrected by me one year earlier. We simply need to copy this to MusicXML appropriately. They are written in all uppercase characters.
- [x] Get the structure information from the lyrics column
- [x] Validity check (duplicate names, uppercase)
- [x] Check these info for instrumental compositions apart from peşrev and sazsemaisi
- [x] Copy these info to MusicXML according to the MusicXML schema.

**Comment by burakuyar** [comment]
Done.

Section information will be imported from symbtrdataextractor.
