### ISSUE TITLE
MusicXML validation

### ISSUE THREAD

**Issue by burakuyar** [burakuyar/MusicXMLConverter#7]
Check how to validate MusicXML schema of musicxml files

**Comment by sertansenturk** [comment]
MTG/SymbTr#2 (thanks to @dspreadbury) and http://musescore.org/en/node/33546 has some explanations on this issue.

**Comment by burakuyar** [comment]
"Right, there is no way in MusicXML 3.0 to state a preference for XSD validation that doesn't cause validation issues when using the DTD. This is something we could change in a future version of MusicXML if there is enough interest."
Michael Good
VP of R&D
MakeMusic, Inc.

**Comment by burakuyar** [comment]
Almost all of the validation issues are related to the element orders. For example, the following two xml data is different than each other according to the MusicXML schema:

```
<X>
      <Y>
      <Z>
</X>

<X>
      <Z>
      <Y>
</X>
```

I'm changing the code to create appropriate outputs when I receive a validation warning. However, some parts of the code is very very hard to change because there are related/connected calculations which are not suitable to interrupt.

I will ask about this to MusicXML community.
