### ISSUE TITLE
Add Additional Metadata from MusicBrainz and mus2-alfa

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#8]
If we add the mbids for the composition we can directly relate/fetch relevant metadata easily.

The work-SymbTr relations for the whole CompMusic collection is here: MTG/dunya#174

The relevant metadata in mus2-alfa and MusicBrainz is being checked/matched as explained in MTG/dunya#180 and MTG/dunya#200.

**Comment by sertansenturk** [comment]
We are postponing this since this is not critical and Burak can use his time for more important stuff right now (e.g. annotations)

**Comment by sertansenturk** [comment]
Add to the relation fileld: http://www.musicxml.com/UserManuals/MusicXML/MusicXML.htm#EL-MusicXML-relation.htm Use https://github.com/MTG/SymbTr/blob/master/symbTr_mbid.json to find the mbid. print the link (e.g. http://musicbrainz.org/work/d6bdf2c1-9264-4b31-8dfd-519dae1bb840)

**Comment by burakuyar** [comment]
Text metadata is obtained from Mu2 files by https://github.com/sertansenturk/symbtrdataextractor and the MusicBrainz work links are added from https://github.com/MTG/SymbTr/blob/master/symbTr_mbid .

**Comment by sertansenturk** [comment]
can we close it?
