### ISSUE TITLE
Copy the structure information in vocal compositions 

### ISSUE THREAD

**Issue by sertansenturk** [burakuyar/MusicXMLConverter#9]
The instrumental sections in the vocal compositions has the same structure explained in #5 . 

Within lyrics, there is one space character at the end of the syllables that occur at word endings and two space characters at the end of the verses. The ending of the verse should be placed just before the bridge or the start measure of the next verse.

**Comment by burakuyar** [comment]
Sections are tagged basically according to lyric/non-lyric information. We are not checking the melody currently. This can be worked on later. 

The sections are labeled with an index sequentially, without checking the contents (i.e. two consecutive nakarats will have consecutive numbers even though they are the same section)
